---
- hosts: 172.16.0.15
  connection: ssh

  pre_tasks:
    - apt: upgrade=dist
    - apt: name={{ item }} state=latest
      with_items:
        - htop
        - git
        - sudo
        - bash-completion
        - git-completion
        - hdparm
    - user: name=afterdesign groups=sudo append=yes

  roles:
    - systemd
    - cups
    # - backup
    # - plex
    # - brother-scanner
    # - brother-printer
    # - mounting
    # - energy-saving
