---
- hosts: 172.16.0.15
  connection: ssh
  vars:
    backup_mount: /media/backup

  pre_tasks:
    - apt: upgrade=dist
    - apt: name={{ item }} state=latest
      with_items:
        - htop
        - git
        - sudo
        - bash-completion
        - git-completion
        - hdparm
        - avahi-daemon
        - firmware-linux-nonfree
        - firmware-realtek

    - user: name=afterdesign groups=sudo append=yes

  roles:
    - systemd
    - cups
    - energy-saving
    - brother-scanner
    - backup
    - mounting

    # - plex
    # - energy-saving
