---
- hosts: 10.0.1.7
  connection: ssh
  user: afterdesign
  sudo: yes

  pre_tasks:
    - name: Upgrade packages
      apt: upgrade=dist
    - name: Install packages
      apt: name={{ item }} state=installed
      with_items:
        - htop
        - git

  roles:
    - brother
    - mounting
    - energy-saving