---
- hosts: 10.0.1.7
  connection: ssh
  sudo: yes

  pre_tasks:
    - name: Upgrade packages
      apt: upgrade=dist
    - name: Install packages
      apt: name={{ item }} state=installed
      with_items:
        - htop
        - git
    - name: Remove packages
      apt: name={{ item }} state=absent purge=yes
      with_items:
        - update-notifier-common
        - landscape-common
        - update-manager-core
        - ubuntu-release-upgrader-core

  roles:
    - brother-scanner
    - brother-printer
    - mounting
    - energy-saving
