---
  - name: create {{ scans_directory }} directory
    file:
      dest: "{{ scans_directory }}"
      mode: 777
      owner: afterdesign
      group: afterdesign
      state: directory

  - name: install netatalk
    apt:
      pkg: netatalk
      state: latest

  - name: copy config afpd
    copy:
      src: "afpd.conf"
      dest: "/etc/netatalk/afpd.conf"

  - name: copy config AppleVolumes
    template:
      src: "AppleVolumes.j2"
      dest: "/etc/netatalk/AppleVolumes.default"

  - name: Restart netatalk
    service:
      name: netatalk
      state: restarted
