---
- name: install laptop-mode-tools
  apt: pkg=laptop-mode-tools state=latest

- name: setup laptop-mode-tools
  copy: src=laptop-mode.conf dest=/etc/laptop-mode/laptop-mode.conf backup=yes
  notify: restart laptop-tools
